5 sql/python-sqlite-sqlalchemy/project/examples/example_3/app/customers/routes.py
from flask import Blueprint
from flask import render_template
from sqlalchemy import func
from app import db
from app.models import Customer
from app.models import Invoice
from sqlalchemy import desc


# Setup the Blueprint
customers_bp = Blueprint(
    "customers_bp",
    __name__,
    template_folder="templates",
    static_folder="static",
)


@customers_bp.route("/customers", methods=["GET"])
@customers_bp.route("/customers/<int:customer_id>", methods=["GET"])
def customers(customer_id=None):

    # Start the query for customers
    query = db.session.query(
        Customer, func.sum(Invoice.total).label("invoices_total")
    ).join(Invoice)

    # Display the albums for the customer passed?
    if customer_id is not None:
        query = query.filter(Customer.customer_id == customer_id)

    results = (
        query.group_by(Customer.customer_id)
        .order_by(desc(func.sum(Invoice.total)))
        .all()
    )
    return render_template("customers.html", results=results)

5 sql/python-sqlite-sqlalchemy/project/examples/example_3/app/customers/templates/customers.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
  <div class="m-4">
    {# display just the playlists #}
    {% if results|length > 1 %}
    <table class="table table-striped table-bordered table-hover table-sm">
      <caption>Customers</caption>
      <thead>
        <tr>
          <th>Customer Name</th>
          <th class="text-center">Email</th>
          <th class="text-center">Total Value Of Orders</th>
        </tr>
      </thead>
      <tbody>
        {% for customer, invoices_total in results %}
        <tr>
          <td>
            <a href="{{url_for('customers_bp.customers', customer_id=customer.customer_id)}}">
              {{ customer.full_name }}
            </a>
          </td>
          <td class="text-center">{{ customer.email }}</td>
          <td class="text-right">{{ '%.2f'|format(invoices_total) }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {# display the playlist name and the tracks #}
    {% else %}
    {% set customer, invoices_total = results[0] %}
    <div class="card" style="width: 18rem;">
      <div class="card-header">Customer</div>
      <div class="card-body">
        <p class="card-text">Name:&nbsp;{{ customer.full_name }}</p>
        <p class="card-text">Address:&nbsp;{{ customer.address }}</p>
        <p class="card-text">
          City:&nbsp;{{ customer.city }},&nbsp;{{ customer.state }}&nbsp;&nbsp;{{ customer.postal_code }}</p>
        <p class="card-text">Phone:&nbsp;{{ customer.phone }}</p>
        <p class="card-text">Email:&nbsp;{{ customer.email }}</p>
        <p class="card-text">Support Rep:&nbsp;
          <a href="{{url_for('employees_bp.employees', employee_id=customer.support_rep_id)}}">
            {{ customer.support_rep.full_name }}
          </a>
        </p>
      </div>
    </div>
    <table class="table table-striped table-bordered table-hover table-sm">
      <caption>Invoices</caption>
      <thead>
        <tr>
          <th class="text-center">Invoice Id</th>
          <th class="text-center">Invoice Date</th>
          <th class="text-right">Total</th>
        </tr>
      </thead>
      <tbody>
        {% set invoices = customer.invoices %}
        {% for invoice in invoices %}
        <tr>
          <td class="text-center">
            <a href="{{url_for('invoices_bp.invoices', invoice_id=invoice.invoice_id)}}">
              {{ invoice.invoice_id}}
            </a>
          </td>
          <td class="text-center">{{ invoice.invoice_date }}</td>
          <td class="text-right">{{ invoice.total }}</td>
        </tr>
        {% endfor %}
        <tr>
          <td></td>
          <td class="text-right">Total</td>
          <td class="text-right">{{ invoices_total }}</td>
        </tr>
      </tbody>
    </table>
    {% endif %}
  </div>
</div>
{% endblock %}